version: '3.3'
services:
  mysql-database:
    image: mysql:8.3.0-oracle
    restart: always
    environment:
      MYSQL_DATABASE: 'wallet'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'W@LL3T'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: